# -*- coding: utf-8 -*-
from .macho import (
    is_macho_binary,
    get_load_dylibs,
    inject_lc_load_dylib,
    get_macho_summary,
    is_fat_binary,
    thin_binary_to_arm64,
    get_arch_slices,
    is_arm64_slice,
    list_all_archs,
    has_rpath,
    inject_rpath,
    get_main_executable,
    is_ipa_encrypted,
    inject_code_signature,
)
from .plist_editor import load_plist, load_plist_safe, save_plist, save_plist_safe
from .substrate import safe_patch_dylib_path, inject_substrate, patch_tweak_substrate_dependencies
from .tweak_injector import inject_tweaks, check_header_space, count_modules_in_tweak, verify_binary_architecture
from .entitlements import generate_custom_entitlements, extract_team_id
from .advanced_patches import apply_advanced_patches, check_patch_availability
from .patch_strings import patch_strings_in_binary
from .ipa_utils import (
    extract_ipa_with_progress,
    pack_ipa_with_progress,
    make_temp_ipa_dir,
    get_platform_temp_dir,
    find_app_dir,
    pick_ipa_file,
    pick_tweak_file,
    pick_icon_file,
    pick_substrate_file,
    pick_cert_zip,
    ProgressBar,
)
from .signature import clean_signature_files, sign_app_bundle_with_path
from .constants import (
    MIN_HEADER_PADDING,
    LC_LOAD_DYLIB,
    LC_RPATH,
    LC_CODE_SIGNATURE,
    MH_MAGIC_64,
    MH_CIGAM_64,
    MH_MAGIC_32,
    MH_CIGAM_32,
    FAT_MAGIC,
    FAT_CIGAM,
    VERSION,
    PatchConfig,
)

__all__ = [
    'is_macho_binary',
    'get_load_dylibs',
    'inject_lc_load_dylib',
    'get_macho_summary',
    'is_fat_binary',
    'thin_binary_to_arm64',
    'get_arch_slices',
    'is_arm64_slice',
    'list_all_archs',
    'has_rpath',
    'inject_rpath',
    'get_main_executable',
    'is_ipa_encrypted',
    'inject_code_signature',
    'load_plist',
    'load_plist_safe',
    'save_plist',
    'save_plist_safe',
    'safe_patch_dylib_path',
    'inject_substrate',
    'patch_tweak_substrate_dependencies',
    'inject_tweaks',
    'check_header_space',
    'count_modules_in_tweak',
    'verify_binary_architecture',
    'generate_custom_entitlements',
    'extract_team_id',
    'apply_advanced_patches',
    'check_patch_availability',
    'patch_strings_in_binary',
    'extract_ipa_with_progress',
    'pack_ipa_with_progress',
    'make_temp_ipa_dir',
    'get_platform_temp_dir',
    'find_app_dir',
    'pick_ipa_file',
    'pick_tweak_file',
    'pick_icon_file',
    'pick_substrate_file',
    'pick_cert_zip',
    'ProgressBar',
    'clean_signature_files',
    'sign_app_bundle_with_path',
    'MIN_HEADER_PADDING',
    'LC_LOAD_DYLIB',
    'LC_RPATH',
    'LC_CODE_SIGNATURE',
    'MH_MAGIC_64',
    'MH_CIGAM_64',
    'MH_MAGIC_32',
    'MH_CIGAM_32',
    'FAT_MAGIC',
    'FAT_CIGAM',
    'VERSION',
    'PatchConfig',
]
